Add UserContext
gorhack/tsr pull request #310
Opened 2021-06-04 20:02 UTC by mojo9492

2021-06-04 20:32 UTC, mojo9492 commented
The issue with prettier seems to have been resolved

2021-06-04 23:55 UTC, gorhack commented on client/src/Users/UserApi.ts
> +    // TODO shouldn't need
do we still need this??

2021-06-04 23:56 UTC, gorhack requested changes
Please remove the org information from the drawer menu and the empty tsr user.

2021-06-07 19:09 UTC, mojo9492 commented
Ready @gorhack

2021-06-08 21:18 UTC, gorhack approved these changes

2021-06-08 21:19 UTC, merged